import Head from 'next/head'
import Banner from '../component/Banner/Banner'
import EighthSection from '../component/EighthSection/EighthSection'
import FifthSection from '../component/FifthSection/FifthSection'
import FirstSection from '../component/FirstSection/FirstSection'
import Footer from '../component/Footer/Footer'
import FourthSection from '../component/FourthSection/FourthSection'
import Navbar from '../component/Navbar/Navbar'
import NinethSection from '../component/NinethSection/NinethSection'
import SecondSection from '../component/SecondSection/SecondSection'
import SeventhSection from '../component/SeventhSection.js/SeventhSection'
import SixthSection from '../component/SixthSection/SixthSection'
import ThirdSection from '../component/ThirdSection/ThirdSection'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Legalexbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-[#03142D]'>
        <Navbar/>
        <Banner/>
        <FirstSection/>
        <SecondSection/>
        <ThirdSection/>
        <FourthSection/>
        <FifthSection/>
        <SixthSection/>
        <SeventhSection/>
        <EighthSection/>
        <NinethSection/>
        <Footer/>
      </div>
    </div>
  )
}
