// import Head from "next/head";
import Banner from "../component/Banner/Banner";
import EighthSection from "../component/EighthSection/EighthSection";
import FifthSection from "../component/FifthSection/FifthSection";
import FirstSection from "../component/FirstSection/FirstSection";
import Footer from "../component/Footer/Footer";
import FourthSection from "../component/FourthSection/FourthSection";
import Navbar from "../component/Navbar/Navbar";
import NinethSection from "../component/NinethSection/NinethSection";
import SecondSection from "../component/SecondSection/SecondSection";
import SeventhSection from "../component/SeventhSection.js/SeventhSection";
import SixthSection from "../component/SixthSection/SixthSection";
import ThirdSection from "../component/ThirdSection/ThirdSection";
// import clientPromise from "./api/db/db";
// import { InferGetServerSidePropsType } from "next";
// export async function getServerSideProps(context) {
//   try {
//     await clientPromise;
//     // `await clientPromise` will use the default database passed in the MONGODB_URI
//     // However you can use another database (e.g. myDatabase) by replacing the `await clientPromise` with the following code:
//     //
//     // `const client = await clientPromise`
//     // `const db = client.db("myDatabase")`
//     //
//     // Then you can execute queries against your database like so:
//     // db.find({}) or any of the MongoDB Node Driver commands

//     return {
//       props: { isConnected: true },
//     };
//   } catch (e) {
//     console.error(e);
//     return {
//       props: { isConnected: false },
//     };
//   }
// }
// export default function Home({ isConnected }) {
//   return (
//     <div>
//       <Head>
//         <title>Legalexbox</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <div className="bg-[#03142D]">
//         <Navbar />
//         <Banner />
//         <FirstSection />
//         <SecondSection />
//         <ThirdSection />
//         <FourthSection />
//         <FifthSection />
//         <SixthSection />
//         <SeventhSection />
//         <EighthSection />
//         <NinethSection />
//         <Footer />
//       </div>
//     </div>
//   );
// }

import Head from "next/head";

import { InferGetServerSidePropsType } from "next";
import clientPromise from "./api/db/db";
import React from "react";

export async function getServerSideProps(context) {
  try {
    await clientPromise;
    return {
      props: { isConnected: true },
    };
  } catch (e) {
    console.error(e);
    return {
      props: { isConnected: false },
    };
  }
}

export default function Home({
  isConnected,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {/* <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js with MongoDB!</a>
        </h1> */}

        <div className="bg-[#03142D]">
          <Navbar />
          <Banner />
          <FirstSection />
          <SecondSection />
          <ThirdSection />
          <FourthSection />
          <FifthSection />
          <SixthSection />
          <SeventhSection />
          <EighthSection />
          <NinethSection />
          <Footer />
        </div>
      </main>
    </div>
  );
}
